import "../styles/globals.css";
import NavBar from "../components/NavBar";
import Container from "@mui/material/Container";
import Head from "next/head";

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <NavBar />
      <Container maxWidth='lg'>
        <Component {...pageProps} />
      </Container>
    </>
  );
}

export default MyApp;
