import "../styles/globals.css";
import NavBar from "../components/NavBar";
import Container from "@mui/material/Container";
import Head from "next/head";
import { useEffect, useState } from "react";
import Web3Modal from "web3modal";
import { ethers } from "ethers";

function MyApp({ Component, pageProps }) {
  const [provider, setProvider] = useState();
  const [signer, setSigner] = useState();

  useEffect(() => {
    connect();
  }, []);

  async function connect() {
    const web3Modal = new Web3Modal();
    const connection = await web3Modal.connect();
    const _provider = new ethers.providers.Web3Provider(connection);
    setProvider(_provider);
    setSigner(_provider.getSigner());
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      {signer ? (
        <>
          <NavBar />
          <Container maxWidth='lg'>
            <Component signer={signer} provider={provider} {...pageProps} />
          </Container>
        </>
      ) : (
        ""
      )}
    </>
  );
}

export default MyApp;
